//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by pcp_edit.rc
//
#define IDC_MARGIN_CURSOR               101
#define IDB_MARGIN_ICONS                102
#define IDS_ERROR_FMT_FIND              61754
#define IDS_EDITOP_UNKNOWN              61763
#define IDS_EDITOP_PASTE                61764
#define IDS_EDITOP_DELSELECTION         61765
#define IDS_EDITOP_CUT                  61766
#define IDS_EDITOP_DELETE               61767
#define IDS_EDITOP_TYPING               61768
#define IDS_EDITOP_BACKSPACE            61769
#define IDS_EDITOP_INDENT               61770
#define IDS_EDITOP_DRAGDROP             61771
#define IDS_EDITOP_REPLACE              61772
#define IDS_EDITOP_AUTOINDENT           61773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
